plugin:
    name: 'impulsetechnologies.campaignr::lang.plugin.name'
    description: 'impulsetechnologies.campaignr::lang.plugin.description'
    author: 'Impulse Technologies'
    icon: oc-icon-bullhorn
    homepage: ''
navigation:
    main-menu-item:
        label: 'impulsetechnologies.campaignr::lang.plugin.name'
        url: impulsetechnologies/campaignr/events
        icon: icon-bullhorn
        sideMenu:
            event-create:
                label: 'impulsetechnologies.campaignr::lang.plugin.create'
                url: 'impulsetechnologies/campaignr/events/create'
                icon: icon-plus
            event-list:
                label: 'impulsetechnologies.campaignr::lang.plugin.events'
                url: impulsetechnologies/campaignr/events
                icon: icon-list
            event-calendar:
                label: 'impulsetechnologies.campaignr::lang.plugin.calendar'
                url: 'impulsetechnologies/campaignr/calendar'
                icon: icon-calendar
permissions:
    campaignr.events.edit:
        tab: 'impulsetechnologies.campaignr::lang.permissions.tab'
        label: 'impulsetechnologies.campaignr::lang.permissions.edit'
